enum NativeStorageKey {
    AUTHORIZED_USER = 'AUTHORIZED_USER',
    SHOULD_RELOAD_VOCABULARIES = 'SHOULD_RELOAD_VOCABULARIES',
    UPDATED_VOCABULARY = 'UPDATED_VOCABULARY',
    SET_LEITNER_BOX_EXISTENCE = 'SET_LEITNER_BOX_EXISTENCE',
    VOCAB_SORT = 'VOCAB_SORT',
    SHOULD_RELOAD_LEITNER_ITEMS = 'SHOULD_RELOAD_LEITNER_ITEMS',
}

export default NativeStorageKey;
