enum NativeStorageKey {
    AUTHORIZED_USER = 'AUTHORIZED_USER',
    SHOULD_RELOAD_VOCABULARIES = 'SHOULD_RELOAD_VOCABULARIES',
    UPDATED_VOCABULARY = 'UPDATED_VOCABULARY',
    THEME_MODE = 'THEME_MODE',
}

export default NativeStorageKey;
